### PR TITLE
Telescope doab

### PR DESCRIPTION
**Pull request by aroelo**
Closing https://github.com/The-Academic-Observatory/observatory-platform/issues/304

### CODE REVIEW

**Review by jdddog — COMMENTED** [review]
Hey Aniek, it looks good to me, I just have some questions about the testing environment.

Could you describe why two DAG runs need to be tested? I'm sure you have good reasons for that, I just want to understand them more.

**Comment by aroelo** [comment]
> Hey Aniek, it looks good to me, I just have some questions about the testing environment.
> 
> Could you describe why two DAG runs need to be tested? I'm sure you have good reasons for that, I just want to understand them more.

Yeah definitely, because this is a 'StreamTelescope', it has the following tasks for loading data into BigQuery:
1. bq_load_partition. Load data into a single BigQuery partition
2. bq_delete_old. Delete old rows from the main table.
3. bq_append_new. Append new rows to the main table.

These tasks are slightly different for a first run, compared to a second (or later) run.
Task 1 is skipped for the first run, so the data is just appended to the main table in task 3. The partition and the main table would be the same. Since the first run most likely contains all data from the past up until now this can be big in size, it saves some resources to just add it to the main table and not as a partition as well.
For a later run this is where the data from that current release/file is loaded into a partition.

Task 2 is also skipped for the first run, because there is no old data. 
For a later run the data from the relevant partition(s) is deleted from the main table. It can be 1 partition or multiple partitions, depending on how many partitions have been added since this task last ran (defined by bq_merge_days).

Task 3 is executed for both first and later runs, but for the first run the data is added to the table from a file, while for the later run the data is added from the partition that is created in task 1. 
For a later run the data from the relevant partition(s) is added to the main table. It can be 1 partition or multiple partitions, depending on how many partitions have been added since this task last ran (defined by bq_merge_days).

So, to test whether this is all working correctly it would be good to have 2 dag runs.

**Review by jdddog — CHANGES_REQUESTED** [review]
Hey Aniek, the schema might need updating, I get the following error when running the telescope:
```bash
Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 31016; errors: 1. Please look into the errors[] collection for more details.
Error while reading data, error message: JSON processing encountered too many errors, giving up. Rows: 31016; errors: 1; max bad: 0; error percent: 0
Error while reading data, error message: JSON parsing error in row starting at position 78578184: No such field: oapen.remark.
```

The ability to create a dag run in the observatory test environment looks good. Can we separate those changes into a separate pull request and merge them first? 

The main thing that I would suggest to change for that pull request, is to move the time freezing functionality inside `create_dag_run`. So in `create_dag_run` we would use the `execution_date` parameter to freeze time at the start of the try block in and unfreeze time at the end of the finally block. Then the developer doesn't have to manually add that functionality whenever they use `create_dag_run`.

**Review by jdddog — COMMENTED** [review]
Did you test the DAG in Airflow on the real dataset?

The task fails on bq_append_new (for the period 2018-05-14 to 2021-04-28):

```bash
Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 40549; errors: 1. Please look into the errors[] collection for more details.
Error while reading data, error message: JSON processing encountered too many errors, giving up. Rows: 40549; errors: 1; max bad: 0; error percent: 0
Error while reading data, error message: JSON parsing error in row starting at position 106689313: Repeated field must be imported as a JSON array. Field: oapen.grant.project.
```

**Comment by aroelo** [comment]
> Did you test the DAG in Airflow on the real dataset?
> 
> The DAG fails at the task bq_append_new (for the period 2018-05-14 to 2021-04-28):
> 
> ```shell
> Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 40549; errors: 1. Please look into the errors[] collection for more details.
> Error while reading data, error message: JSON processing encountered too many errors, giving up. Rows: 40549; errors: 1; max bad: 0; error percent: 0
> Error while reading data, error message: JSON parsing error in row starting at position 106689313: Repeated field must be imported as a JSON array. Field: oapen.grant.project.
> ```

Yeah I did, I tested it just before requesting the review, for the period 2018_05_14 to 2021_04_26.
It was also working 9 days ago and then the schema changed when you had a look 7 days ago.

I just checked and in my data there were no entries for the `oapen.grant.project` field. It seems there is 1 entry in the latest one. I apparently set the mode to 'REPEATED' for this field, but did not make it a list.

This is an easy fix, but it did prompt me to have a closer look at the schema/fields. 
There's not really any way to know whether a field is REPEATED or not until they have added an entry that includes a value with their separator '||' in there. I previously checked with:
```python
        list_fields = set()
        for entry in csv_entries:
            for k, v in entry.items():
                if '||' in v:
                    list_fields.add(k)
```
And decided that for those fields the mode should be set to "REPEATED" and they should be made into a list. For the `oapen.grant.project` something went wrong, it was empty when I had a look but still set to REPEATED, probably a manual error.

In general this can give some problems in the future though, if new entries are added and the field mode should be changed from e.g. NULLABLE to REPEATED.

The field names are not that descriptive that you can decipher beforehand whether it will be a list or not.
There are also still 42 columns which are empty:
`
['BITSTREAM ISBN', 'dc.description', 'dc.fundingReference', 'dc.identifier.namewebshop', 'dc.identifier.urlwebshop', 'dc.relation.isreplacedbydouble', 'dc.rights.license', 'dc.rights.licenseurl', 'dc.rights.uri', 'dc.source', 'eperson.firstname', 'eperson.language', 'eperson.lastname', 'eperson.phone', 'eperson.publisher', 'grantor.acronym', 'grantor.doi', 'grantor.name', 'oapen.identifier.downloadUrl', 'oapen.relation.funds', 'publisher.address', 'publisher.authorinstructions', 'publisher.authorinstructions.url', 'publisher.chargeauthors', 'publisher.chargeauthors.url', 'publisher.contact', 'publisher.country', 'publisher.description', 'publisher.email', 'publisher.identifier', 'publisher.name', 'publisher.oabooks.exampleUrl', 'publisher.oabooks.number', 'publisher.oalicense', 'publisher.peerreview.info', 'publisher.peerreviewpolicy', 'publisher.phone', 'publisher.program', 'publisher.register', 'publisher.register.url', 'publisher.status.active', 'publisher.website']
`

The schema I just updated works with the latest data now.

**Comment by jdddog** [comment]
> > Did you test the DAG in Airflow on the real dataset?
> > The DAG fails at the task bq_append_new (for the period 2018-05-14 to 2021-04-28):
> > ```shell
> > Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 40549; errors: 1. Please look into the errors[] collection for more details.
> > Error while reading data, error message: JSON processing encountered too many errors, giving up. Rows: 40549; errors: 1; max bad: 0; error percent: 0
> > Error while reading data, error message: JSON parsing error in row starting at position 106689313: Repeated field must be imported as a JSON array. Field: oapen.grant.project.
> > ```
> 
> Yeah I did, I tested it just before requesting the review, for the period 2018_05_14 to 2021_04_26.
> It was also working 9 days ago and then the schema changed when you had a look 7 days ago.

Ah I see, sorry about that.

> 
> I just checked and in my data there were no entries for the `oapen.grant.project` field. It seems there is 1 entry in the latest one. I apparently set the mode to 'REPEATED' for this field, but did not make it a list.
> 
> This is an easy fix, but it did prompt me to have a closer look at the schema/fields.
> There's not really any way to know whether a field is REPEATED or not until they have added an entry that includes a value with their separator '||' in there. I previously checked with:
> 
> ```python
>         list_fields = set()
>         for entry in csv_entries:
>             for k, v in entry.items():
>                 if '||' in v:
>                     list_fields.add(k)
> ```
> 
> And decided that for those fields the mode should be set to "REPEATED" and they should be made into a list. For the `oapen.grant.project` something went wrong, it was empty when I had a look but still set to REPEATED, probably a manual error.
> 
> In general this can give some problems in the future though, if new entries are added and the field mode should be changed from e.g. NULLABLE to REPEATED.
> 
> The field names are not that descriptive that you can decipher beforehand whether it will be a list or not.
> There are also still 42 columns which are empty:
> `['BITSTREAM ISBN', 'dc.description', 'dc.fundingReference', 'dc.identifier.namewebshop', 'dc.identifier.urlwebshop', 'dc.relation.isreplacedbydouble', 'dc.rights.license', 'dc.rights.licenseurl', 'dc.rights.uri', 'dc.source', 'eperson.firstname', 'eperson.language', 'eperson.lastname', 'eperson.phone', 'eperson.publisher', 'grantor.acronym', 'grantor.doi', 'grantor.name', 'oapen.identifier.downloadUrl', 'oapen.relation.funds', 'publisher.address', 'publisher.authorinstructions', 'publisher.authorinstructions.url', 'publisher.chargeauthors', 'publisher.chargeauthors.url', 'publisher.contact', 'publisher.country', 'publisher.description', 'publisher.email', 'publisher.identifier', 'publisher.name', 'publisher.oabooks.exampleUrl', 'publisher.oabooks.number', 'publisher.oalicense', 'publisher.peerreview.info', 'publisher.peerreviewpolicy', 'publisher.phone', 'publisher.program', 'publisher.register', 'publisher.register.url', 'publisher.status.active', 'publisher.website']`
> 
> The schema I just updated works with the latest data now.

I see. Perhaps we should ask someone at DOAB about which of these fields can contain repeated elements? It would save a lot of time in the future. We can still merge the pull request now (I'll have another look soon).

**Review by jdddog — COMMENTED** [review]
It looks good Aniek, it just needs to be rebased again and we can merge it

**Review by jdddog — APPROVED** [review]

**Pull request merged**
