### PR TITLE
Crossref Fundref use template

### PR DESCRIPTION
**Pull request by aroelo**
Update telescope to use template and update unit tests to use test environment

### CODE REVIEW

**Review by jdddog — CHANGES_REQUESTED** [review]
Nice work Aniek.

The file `observatory-dags/observatory/dags/dags/doi.py needs updating`.

It would be good if you ran the DAG end to end in Airflow with backfill, the DAG run 2014-09-07, fails with the following error message:
```
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/observatory-platform/observatory/platform/telescopes/telescope.py", line 301, in task_callable
    result = func(release, **kwargs)
  File "/opt/observatory-dags/observatory/dags/telescopes/crossref_fundref.py", line 313, in transform
    release.transform()
  File "/opt/observatory-dags/observatory/dags/telescopes/crossref_fundref.py", line 151, in transform
    funders = add_funders_relationships(funders, funders_by_key)
  File "/opt/observatory-dags/observatory/dags/telescopes/crossref_fundref.py", line 555, in add_funders_relationships
    parent, returned_depth = recursive_funders(funders_by_key, funder, 0, 'broader', [])
  File "/opt/observatory-dags/observatory/dags/telescopes/crossref_fundref.py", line 617, in recursive_funders
    sub_funders.pop(-1)
IndexError: pop from empty list
```

**Comment by aroelo** [comment]
> Nice work Aniek.
> 
> The file `observatory-dags/observatory/dags/dags/doi.py needs updating`.
> 
> It would be good if you ran the DAG end to end in Airflow with backfill, the DAG run 2014-09-07, fails with the following error message:
> 
> ```
> Traceback (most recent call last):
>   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 984, in _run_raw_task
>     result = task_copy.execute(context=context)
>   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 113, in execute
>     return_value = self.execute_callable()
>   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
>     return self.python_callable(*self.op_args, **self.op_kwargs)
>   File "/opt/observatory-platform/observatory/platform/telescopes/telescope.py", line 301, in task_callable
>     result = func(release, **kwargs)
>   File "/opt/observatory-dags/observatory/dags/telescopes/crossref_fundref.py", line 313, in transform
>     release.transform()
>   File "/opt/observatory-dags/observatory/dags/telescopes/crossref_fundref.py", line 151, in transform
>     funders = add_funders_relationships(funders, funders_by_key)
>   File "/opt/observatory-dags/observatory/dags/telescopes/crossref_fundref.py", line 555, in add_funders_relationships
>     parent, returned_depth = recursive_funders(funders_by_key, funder, 0, 'broader', [])
>   File "/opt/observatory-dags/observatory/dags/telescopes/crossref_fundref.py", line 617, in recursive_funders
>     sub_funders.pop(-1)
> IndexError: pop from empty list
> ```

Thanks for the review Jamie.
Sorry if it was a bit confusing whether it was ready, I still had to run the DAG end to end myself today.
I ran into those same issues and have fixed them. It is still running for some later versions. I'll let it run until it is up to date as they are all quite fast anyway.

**Comment by aroelo** [comment]
@jdddog I have added documentation and all runs finished successfully, so ready for final review :-)

**Review by jdddog — COMMENTED** [review]
It looks good to me Aniek, we will need to change some of the queries for the DOI workflow, but I will do that in my pull request.

Can you just rebase this and we can merge it?

**Review by jdddog — APPROVED** [review]

**Pull request merged**
