### PR TITLE
Add a custom DagRun sensor

### PR DESCRIPTION
**Pull request by tuanchien**
Currently there are some workflows which have sensors that wait forever.  Many of our current dags run on different dates, and at different intervals.  This hang is possibly caused by:
- monitoring the wrong execution date in the sensor.
- long timeouts (default 7 days) that might have unintended interactions with our dag runs
- potential unintended behaviour with ExternalTaskSensor handling cases when the execution date is wrong

DagRunSensor aims to address those points by making the handling more robust against different execution_date/interval combinations. The DagRunSensor is a sensor that monitors for dag runs of a particular dag_id in the time window [current_execution_date - duration, current_execution_date].
- If the dag_id does not exist in the Airflow db at all, an error is thrown.
- If multiple dag runs are recorded in that window, the LATEST dagrun will be monitored.
- If no dag run is found in the window, it is assumed that the dag did not run in that window, and the sensor will return success (i.e., skip waiting).

The last point allows you to skip on weeks when certain workflows do not run.  But it does mean the dag runs for a monitored dag needs to be in the airflow db before the sensor is executed. So workflows using this sensor should perhaps be scheduled slightly later (e.g., slightly later hour) than the dags being monitored.

If you do not like the behaviour of the last point, perhaps we can discuss alternatives.

### CODE REVIEW

**Review by aroelo — COMMENTED** [review]
Hi @tuanchien, just some general questions.

Which sensors currently hang forever, and is this just due to execution dates that are not lined up?
I made a function a while back that can be used with the execution_date_fn parameter of the ExternalTaskSensor to have the sensor work with crossref metadata, because it has a different schedule interval than the doi workflow (https://github.com/The-Academic-Observatory/observatory-platform/blob/develop/observatory-platform/observatory/platform/utils/workflow_utils.py#L728-L764).
This was implemented and it looks like it was accidentally removed later on when reformatting the workflow to use the template (https://github.com/The-Academic-Observatory/observatory-platform/commit/dad0f43cd8a07e79469bf24336a0ee37d99947b1)

Can this more easily solve the problem, rather than using a custom sensor?

If we do use the custom sensor, what would be the benefit of using a window/time period to monitor the dag runs, rather than just always checking the latest dag run?

**Comment by tuanchien** [comment]
Good questions @aroelo.  I asked @jdddog to tell me which ones failed. Jamie apparently tested it with get_prev_execution_date applied on crossref_metadata_sensor.  I'm not sure of the precise parameters on how that was tested, so he is best to chime in here.

Some example dag runs where it failed:

academic-observatory:
crossref_metadata: 2021-07-07 00:00:00 UTC

doi: 2021-08-15 00:00:00 UTC
  crossref_metadata_sensor

doi: 2021-08-22 00:00:00 UTC
  crossref_metadata_sensor

For oaebu:
google_analytics_anu_press: 2021-08-01 00:00:00 UTC
google_books_anu_press: 2021-08-01 00:00:00 UTC
jstor_anu_press: 2021-08-01 00:00:00 UTC
oapen_irus_uk_anu_press: 2021-07-14 00:00:00 UTC
onix_anu_press: 2021-08-22 00:00:00 UTC
ucl_discovery_ucl_press: 2021-08-01 00:00:00 UTC (only for UCL)

onix_workflow_anu_press: 2021-08-22 00:00:00 UTC
  google_analytics_anu_press_sensor
  google_books_anu_press_sensor
  jstor_anu_press_sensor
  oapen_irus_uk_anu_press_sensor
  onix_anu_press_sensor

My suspicion is it is still to do with execution dates not lining up.  It might have been compounded by the timeout being set too high as well (7 days).  If we have mixed schedule intervals, e.g., monthly and weekly, the monthly start dates might be fixed on a specific day of the month, whereas a weekly one is going to jump around in terms of calendar day of the month.  If the only execution_date you have access to is the one for the current dag run, and you try to calculate backwards using that, you might still land on the wrong day if the phases don't line up.  E.g., if the current execution day is (2021,9,8) and you are looking at (2021,9,1) for a dag that runs weekly. But if that dag ran on (2021,8,30), then the next dagrun (+7 days) would have fallen on (2021,9,6), which would not be the date we would be monitoring.

The custom sensor still looks for the latest execution of the dag we are trying to monitor, but we confine ourselves to a time window.  We do not need to attempt to calculate the previous execution date since it just looks through the entire window leading up to the current execution date, and then takes the latest dagrun it finds.  If it doesn't find one, then presumably that dag was not scheduled to run during that timeframe, and we skip waiting. ExternalSensorTask would have just retried until timeout (after 7 days if using default) and then the workflow would have just failed.

**Comment by jdddog** [comment]
> Hi @tuanchien, just some general questions.
> 
> Which sensors currently hang forever, and is this just due to execution dates that are not lined up?
> I made a function a while back that can be used with the execution_date_fn parameter of the ExternalTaskSensor to have the sensor work with crossref metadata, because it has a different schedule interval than the doi workflow (https://github.com/The-Academic-Observatory/observatory-platform/blob/develop/observatory-platform/observatory/platform/utils/workflow_utils.py#L728-L764).
> This was implemented and it looks like it was accidentally removed later on when reformatting the workflow to use the template ([dad0f43](https://github.com/The-Academic-Observatory/observatory-platform/commit/dad0f43cd8a07e79469bf24336a0ee37d99947b1))
> 
> Can this more easily solve the problem, rather than using a custom sensor?
> 
> If we do use the custom sensor, what would be the benefit of using a window/time period to monitor the dag runs, rather than just always checking the latest dag run?

Yeah I missed it and forgot to port it over when refactoring the DOI Workflow to use the telescope template sorry, although I did test it after that.

It has a problem when the execution date of the waiting DAG crosses over into the month after the execution date of the DAG that is being waited on, because the closest date that matches the cron expression is now in the next month, but the first DAG hasn't run in that month yet.

For instance, if the execution date of the first dag is "2021-08-07" with schedule "0 0 7 * *" and the execution of the second dag is "2021-09-05" with a "@weekly" schedule then the sensor will succeed, finding "2021-08-07". However, when the second dag has an execution date of "2021-09-12", then it will return "2021-09-07", when it should be returning "2021-08-07", because the dag run for the first dag for "2021-09-07" hasn't run yet.

Here are a few test cases to illustrate it. Cases 1 & 2 succeed, however cases 3-5 fail.
```python
import pendulum
from airflow import DAG
from airflow.operators.bash import BashOperator
from airflow.sensors.external_task_sensor import ExternalTaskSensor
from airflow.utils.state import State

from observatory.platform.utils.test_utils import (
    ObservatoryEnvironment,
    ObservatoryTestCase,
)
from observatory.platform.utils.workflow_utils import get_prev_execution_date

FIRST_DAG_SCHEDULE_INTERVAL = "0 0 7 * *"


def first_dag(
    dag_id="first_dag", schedule_interval=FIRST_DAG_SCHEDULE_INTERVAL, start_date=pendulum.datetime(2020, 6, 7)
):
    with DAG(
        dag_id=dag_id, schedule_interval=schedule_interval, default_args={"start_date": start_date,}, catchup=False,
    ) as dag:
        task1 = BashOperator(task_id="trigger", bash_command="echo 'hello'")

    return dag


def second_dag(dag_id="second_dag", schedule_interval="@weekly", start_date=pendulum.datetime(2020, 8, 30)):
    with DAG(
        dag_id=dag_id, schedule_interval=schedule_interval, default_args={"start_date": start_date,}, catchup=False,
    ) as dag:
        # Sensors
        sensor = ExternalTaskSensor(
            task_id="first_dag_sensor",
            external_dag_id="first_dag",
            execution_date_fn=lambda execution_date: get_prev_execution_date(
                FIRST_DAG_SCHEDULE_INTERVAL, execution_date
            ),
            mode="reschedule",
        )

        task1 = BashOperator(task_id="run", bash_command="echo 'world'")
        sensor >> task1

    return dag


class TestSensorSolution(ObservatoryTestCase):
    def test_case1(self):
        env = ObservatoryEnvironment()
        with env.create():
            execution_date = pendulum.datetime(2021, 8, 7)
            dag = first_dag()
            with env.create_dag_run(dag=dag, execution_date=execution_date):
                ti = env.run_task("trigger", dag, execution_date=execution_date)
                self.assertEqual(ti.state, State.SUCCESS)

            execution_date = pendulum.datetime(2021, 8, 29)
            dag = second_dag()
            with env.create_dag_run(dag=dag, execution_date=execution_date):
                ti = env.run_task("first_dag_sensor", dag, execution_date=execution_date)
                self.assertEqual(ti.state, State.SUCCESS)

                ti = env.run_task("run", dag, execution_date=execution_date)
                self.assertEqual(ti.state, State.SUCCESS)

    def test_case2(self):
        env = ObservatoryEnvironment()
        with env.create():
            execution_date = pendulum.datetime(2021, 8, 7)
            dag = first_dag()
            with env.create_dag_run(dag=dag, execution_date=execution_date):
                ti = env.run_task("trigger", dag, execution_date=execution_date)
                self.assertEqual(ti.state, State.SUCCESS)

            execution_date = pendulum.datetime(2021, 9, 5)
            dag = second_dag()
            with env.create_dag_run(dag=dag, execution_date=execution_date):
                ti = env.run_task("first_dag_sensor", dag, execution_date=execution_date)
                self.assertEqual(ti.state, State.SUCCESS)

                ti = env.run_task("run", dag, execution_date=execution_date)
                self.assertEqual(ti.state, State.SUCCESS)

    def test_case3(self):
        env = ObservatoryEnvironment()
        with env.create():
            execution_date = pendulum.datetime(2021, 8, 7)
            dag = first_dag()
            with env.create_dag_run(dag=dag, execution_date=execution_date):
                ti = env.run_task("trigger", dag, execution_date=execution_date)
                self.assertEqual(ti.state, State.SUCCESS)

            execution_date = pendulum.datetime(2021, 9, 12)
            dag = second_dag()
            with env.create_dag_run(dag=dag, execution_date=execution_date):
                ti = env.run_task("first_dag_sensor", dag, execution_date=execution_date)
                self.assertEqual(ti.state, State.SUCCESS)

                ti = env.run_task("run", dag, execution_date=execution_date)
                self.assertEqual(ti.state, State.SUCCESS)

    def test_case4(self):
        env = ObservatoryEnvironment()
        with env.create():
            execution_date = pendulum.datetime(2021, 8, 7)
            dag = first_dag()
            with env.create_dag_run(dag=dag, execution_date=execution_date):
                ti = env.run_task("trigger", dag, execution_date=execution_date)
                self.assertEqual(ti.state, State.SUCCESS)

            execution_date = pendulum.datetime(2021, 9, 19)
            dag = second_dag()
            with env.create_dag_run(dag=dag, execution_date=execution_date):
                ti = env.run_task("first_dag_sensor", dag, execution_date=execution_date)
                self.assertEqual(ti.state, State.SUCCESS)

                ti = env.run_task("run", dag, execution_date=execution_date)
                self.assertEqual(ti.state, State.SUCCESS)

    def test_case5(self):
        env = ObservatoryEnvironment()
        with env.create():
            execution_date = pendulum.datetime(2021, 8, 7)
            dag = first_dag()
            with env.create_dag_run(dag=dag, execution_date=execution_date):
                ti = env.run_task("trigger", dag, execution_date=execution_date)
                self.assertEqual(ti.state, State.SUCCESS)

            execution_date = pendulum.datetime(2021, 9, 26)
            dag = second_dag()
            with env.create_dag_run(dag=dag, execution_date=execution_date):
                ti = env.run_task("first_dag_sensor", dag, execution_date=execution_date)
                self.assertEqual(ti.state, State.SUCCESS)

                ti = env.run_task("run", dag, execution_date=execution_date)
                self.assertEqual(ti.state, State.SUCCESS)
```

**Review by jdddog — CHANGES_REQUESTED** [review]
Hey Tuan, it looks good to me. For the race condition problem it would be good to have a window (e.g. 5 minutes) where the sensor waits to check for the existence of the first DAG.

I also need to double check that a DAG run is created for a DAG run when a task is queued but not yet executed, which can occur for Crossref Metadata.

**Comment by tuanchien** [comment]
Added:
- ability to disable dag db check (mostly for people to do testing),
- simple grace period mechanism to retry querying for execution dates as an alternative to scheduling workflows later, in case of a race to enter dagrun info into the Airflow db

**Review by jdddog — DISMISSED** [review]
It looks good to me Tuan, it just needs rebasing.

**Comment by aroelo** [comment]
> > Hi @tuanchien, just some general questions.
> > Which sensors currently hang forever, and is this just due to execution dates that are not lined up?
> > I made a function a while back that can be used with the execution_date_fn parameter of the ExternalTaskSensor to have the sensor work with crossref metadata, because it has a different schedule interval than the doi workflow (https://github.com/The-Academic-Observatory/observatory-platform/blob/develop/observatory-platform/observatory/platform/utils/workflow_utils.py#L728-L764).
> > This was implemented and it looks like it was accidentally removed later on when reformatting the workflow to use the template ([dad0f43](https://github.com/The-Academic-Observatory/observatory-platform/commit/dad0f43cd8a07e79469bf24336a0ee37d99947b1))
> > Can this more easily solve the problem, rather than using a custom sensor?
> > If we do use the custom sensor, what would be the benefit of using a window/time period to monitor the dag runs, rather than just always checking the latest dag run?
> 
> Yeah I missed it and forgot to port it over when refactoring the DOI Workflow to use the telescope template sorry, although I did test it after that.
> 
> It has a problem when the execution date of the waiting DAG crosses over into the month after the execution date of the DAG that is being waited on, because the closest date that matches the cron expression is now in the next month, but the first DAG hasn't run in that month yet.
> 
> For instance, if the execution date of the first dag is "2021-08-07" with schedule "0 0 7 * *" and the execution of the second dag is "2021-09-05" with a "weekly" schedule then the sensor will succeed, finding "2021-08-07". However, when the second dag has an execution date of "2021-09-12", then it will return "2021-09-07", when it should be returning "2021-08-07", because the dag run for the first dag for "2021-09-07" hasn't run yet.
> 
> Here are a few test cases to illustrate it. Cases 1 & 2 succeed, however cases 3-5 fail.
> 
> ```python
> import pendulum
> from airflow import DAG
> from airflow.operators.bash import BashOperator
> from airflow.sensors.external_task_sensor import ExternalTaskSensor
> from airflow.utils.state import State
> 
> from observatory.platform.utils.test_utils import (
>     ObservatoryEnvironment,
>     ObservatoryTestCase,
> )
> from observatory.platform.utils.workflow_utils import get_prev_execution_date
> 
> FIRST_DAG_SCHEDULE_INTERVAL = "0 0 7 * *"
> 
> 
> def first_dag(
>     dag_id="first_dag", schedule_interval=FIRST_DAG_SCHEDULE_INTERVAL, start_date=pendulum.datetime(2020, 6, 7)
> ):
>     with DAG(
>         dag_id=dag_id, schedule_interval=schedule_interval, default_args={"start_date": start_date,}, catchup=False,
>     ) as dag:
>         task1 = BashOperator(task_id="trigger", bash_command="echo 'hello'")
> 
>     return dag
> 
> 
> def second_dag(dag_id="second_dag", schedule_interval="@weekly", start_date=pendulum.datetime(2020, 8, 30)):
>     with DAG(
>         dag_id=dag_id, schedule_interval=schedule_interval, default_args={"start_date": start_date,}, catchup=False,
>     ) as dag:
>         # Sensors
>         sensor = ExternalTaskSensor(
>             task_id="first_dag_sensor",
>             external_dag_id="first_dag",
>             execution_date_fn=lambda execution_date: get_prev_execution_date(
>                 FIRST_DAG_SCHEDULE_INTERVAL, execution_date
>             ),
>             mode="reschedule",
>         )
> 
>         task1 = BashOperator(task_id="run", bash_command="echo 'world'")
>         sensor >> task1
> 
>     return dag
> 
> 
> class TestSensorSolution(ObservatoryTestCase):
>     def test_case1(self):
>         env = ObservatoryEnvironment()
>         with env.create():
>             execution_date = pendulum.datetime(2021, 8, 7)
>             dag = first_dag()
>             with env.create_dag_run(dag=dag, execution_date=execution_date):
>                 ti = env.run_task("trigger", dag, execution_date=execution_date)
>                 self.assertEqual(ti.state, State.SUCCESS)
> 
>             execution_date = pendulum.datetime(2021, 8, 29)
>             dag = second_dag()
>             with env.create_dag_run(dag=dag, execution_date=execution_date):
>                 ti = env.run_task("first_dag_sensor", dag, execution_date=execution_date)
>                 self.assertEqual(ti.state, State.SUCCESS)
> 
>                 ti = env.run_task("run", dag, execution_date=execution_date)
>                 self.assertEqual(ti.state, State.SUCCESS)
> 
>     def test_case2(self):
>         env = ObservatoryEnvironment()
>         with env.create():
>             execution_date = pendulum.datetime(2021, 8, 7)
>             dag = first_dag()
>             with env.create_dag_run(dag=dag, execution_date=execution_date):
>                 ti = env.run_task("trigger", dag, execution_date=execution_date)
>                 self.assertEqual(ti.state, State.SUCCESS)
> 
>             execution_date = pendulum.datetime(2021, 9, 5)
>             dag = second_dag()
>             with env.create_dag_run(dag=dag, execution_date=execution_date):
>                 ti = env.run_task("first_dag_sensor", dag, execution_date=execution_date)
>                 self.assertEqual(ti.state, State.SUCCESS)
> 
>                 ti = env.run_task("run", dag, execution_date=execution_date)
>                 self.assertEqual(ti.state, State.SUCCESS)
> 
>     def test_case3(self):
>         env = ObservatoryEnvironment()
>         with env.create():
>             execution_date = pendulum.datetime(2021, 8, 7)
>             dag = first_dag()
>             with env.create_dag_run(dag=dag, execution_date=execution_date):
>                 ti = env.run_task("trigger", dag, execution_date=execution_date)
>                 self.assertEqual(ti.state, State.SUCCESS)
> 
>             execution_date = pendulum.datetime(2021, 9, 12)
>             dag = second_dag()
>             with env.create_dag_run(dag=dag, execution_date=execution_date):
>                 ti = env.run_task("first_dag_sensor", dag, execution_date=execution_date)
>                 self.assertEqual(ti.state, State.SUCCESS)
> 
>                 ti = env.run_task("run", dag, execution_date=execution_date)
>                 self.assertEqual(ti.state, State.SUCCESS)
> 
>     def test_case4(self):
>         env = ObservatoryEnvironment()
>         with env.create():
>             execution_date = pendulum.datetime(2021, 8, 7)
>             dag = first_dag()
>             with env.create_dag_run(dag=dag, execution_date=execution_date):
>                 ti = env.run_task("trigger", dag, execution_date=execution_date)
>                 self.assertEqual(ti.state, State.SUCCESS)
> 
>             execution_date = pendulum.datetime(2021, 9, 19)
>             dag = second_dag()
>             with env.create_dag_run(dag=dag, execution_date=execution_date):
>                 ti = env.run_task("first_dag_sensor", dag, execution_date=execution_date)
>                 self.assertEqual(ti.state, State.SUCCESS)
> 
>                 ti = env.run_task("run", dag, execution_date=execution_date)
>                 self.assertEqual(ti.state, State.SUCCESS)
> 
>     def test_case5(self):
>         env = ObservatoryEnvironment()
>         with env.create():
>             execution_date = pendulum.datetime(2021, 8, 7)
>             dag = first_dag()
>             with env.create_dag_run(dag=dag, execution_date=execution_date):
>                 ti = env.run_task("trigger", dag, execution_date=execution_date)
>                 self.assertEqual(ti.state, State.SUCCESS)
> 
>             execution_date = pendulum.datetime(2021, 9, 26)
>             dag = second_dag()
>             with env.create_dag_run(dag=dag, execution_date=execution_date):
>                 ti = env.run_task("first_dag_sensor", dag, execution_date=execution_date)
>                 self.assertEqual(ti.state, State.SUCCESS)
> 
>                 ti = env.run_task("run", dag, execution_date=execution_date)
>                 self.assertEqual(ti.state, State.SUCCESS)
> ```

Ah I see, thanks for writing out those tests Jamie!
My bad for not picking this up, I must have made a thinking error in execution dates vs actual run dates and not properly tested it.
If it's not being used and doesn't work as expected, could you maybe remove the discussed function from workflow_utils in this PR then Tuan? :-)
Or I can remove it later in another PR.

**Comment by tuanchien** [comment]
@aroelo ok no problem. I will remove it in this PR then.

**Review by jdddog — APPROVED** [review]

**Pull request merged**
